"""add nickname to user and metadata to product

Revision ID: 2c2081fafd12
Revises: 56d72e4c7a5b
Create Date: 2026-01-26 23:47:05.162514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c2081fafd12'
down_revision: Union[str, Sequence[str], None] = '56d72e4c7a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('chat_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('nickname', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname')
    op.drop_column('products', 'chat_count')
    op.drop_column('products', 'likes')
    op.drop_column('products', 'views')
    # ### end Alembic commands ###
