"""Add product details

Revision ID: 4a0b9200fcb0
Revises: 1b2db70ffc6f
Create Date: 2026-01-20 22:30:21.544639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0b9200fcb0'
down_revision: Union[str, Sequence[str], None] = '1b2db70ffc6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_main', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('category_medium', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('category_small', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('condition', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('tags', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'tags')
    op.drop_column('products', 'condition')
    op.drop_column('products', 'category_small')
    op.drop_column('products', 'category_medium')
    op.drop_column('products', 'category_main')
    # ### end Alembic commands ###
